Le_Domain='idjkt.szpremium.my.id'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/1792798137/280063315877'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/1792798137/280063315877'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0321f49cb0955f7b8135d6ccce863cfb3acd'
Le_CertCreateTime='1718880532'
Le_CertCreateTimeStr='2024-06-20T10:48:52Z'
Le_NextRenewTimeStr='2024-08-18T10:48:52Z'
Le_NextRenewTime='1723978132'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/etc/xray/xray.key'
Le_ReloadCmd=''
Le_RealFullChainPath='/etc/xray/xray.crt'
