[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgt9JzDMZsw4kzaCO4uzno_hpd6WyHl40VSQwmMmjSHu-f_ZoB3hCuMff_TEcEFNmSnJEKvgyHvJj19HXyE41mukm1wPbfCJj_vsSTBJz48jr-685ehjJl_pbPtw1EyMDjPh_V1TSc2ra5OKZJs-VW1ESDrq4ZTZfswaCgYKARkSARASFQHGX2MiZvN-i1qZXE-diMVmcC6n1Q0174","token_type":"Bearer","refresh_token":"1//0grQ5ja__cHVYCgYIARAAGBASNwF-L9IrID7_Slumh-27S23f5CWyT7s8xLXwrXrIetDSNcaNcRCunfDagoB6cJCH1hUekmhvZJk","expiry":"2024-07-01T19:58:05.353440461+07:00"}

