[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgsdaWShA2AnJO7dLWhSpB5RcUBfrypJu2b0nShznpfqVvmEW1ch_LlQr-GYekw-Sbaoxn3En6jAhJcWWPJmOszgsi6AP07fffCiGU9hCwOPjYHZh8FsevsDjN8zMGwJ1DOjt772Ezn3cKChMCs2Rt-IAxIGNFxxCMkaCgYKAeESARASFQHGX2MiIV0zC3MV_j6YegPRLO2Iqg0174","token_type":"Bearer","refresh_token":"1//0grQ5ja__cHVYCgYIARAAGBASNwF-L9IrID7_Slumh-27S23f5CWyT7s8xLXwrXrIetDSNcaNcRCunfDagoB6cJCH1hUekmhvZJk","expiry":"2024-06-30T23:57:20.351146561+07:00"}

