[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXooCgu5V1v4firWNmPqEck6ixwvjK9EEt76UMGJ7gEiwFE9Et_3k5XXio4mX8IbEGDOO-JCZIg2HCSdU49UmBchYnXHagpvW7gvyBtCJY-AkcEN87iWGstgvK2ACL8q56g2xAHbsTrHF2gsXPL_CPm7V4X5rE3zIpQ9HnIaCgYKAbwSARASFQHGX2MibQxXEKMY98t7EmFmeMswSA0174","token_type":"Bearer","refresh_token":"1//0grQ5ja__cHVYCgYIARAAGBASNwF-L9IrID7_Slumh-27S23f5CWyT7s8xLXwrXrIetDSNcaNcRCunfDagoB6cJCH1hUekmhvZJk","expiry":"2024-07-01T15:57:58.399170438+07:00"}

